name: dalton_wade
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/language/
    
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic